version: '3.8'
services:
  service:
    build: ./
    command: ./service
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
