services:
  service:
    image: service:local
    container_name: s-backend
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8080:8080"
    # restart: on-failure
  postgresql:
    image: postgres:14-alpine
    container_name: s-psql
    environment:
      POSTGRES_DB: service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d service -U user"]
      interval: 10s
      timeout: 5s
      retries: 3
    
networks:
  server-side: